name: mesh
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.4=hd7fb8db_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.19=hbb43b14_0
  - packaging=25.0=py310haa95532_1
  - pip=26.0.1=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.10.2=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - asttokens==3.0.1
      - attrs==25.4.0
      - blinker==1.9.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - comm==0.2.3
      - configargparse==1.7.1
      - cython==3.2.4
      - dash==4.0.0
      - decorator==5.2.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - flask==3.1.2
      - glfw==2.10.0
      - idna==3.11
      - importlib-metadata==8.7.1
      - ipython==8.38.0
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - multipledispatch==1.0.0
      - narwhals==2.16.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numpy==2.2.6
      - open3d==0.19.0
      - parso==0.8.6
      - pillow==12.1.1
      - platformdirs==4.7.0
      - plotly==6.5.2
      - prompt-toolkit==3.0.52
      - pure-eval==0.2.3
      - pyglfw==0.2.2
      - pygments==2.19.2
      - pyopengl==3.1.10
      - pyopengl-accelerate==3.1.10
      - pyrr==0.10.3
      - python-fcl==0.7.0.10
      - referencing==0.37.0
      - requests==2.32.5
      - retrying==1.4.2
      - rpds-py==0.30.0
      - scipy==1.15.3
      - stack-data==0.6.3
      - traitlets==5.14.3
      - trimesh==4.11.2
      - typing-extensions==4.15.0
      - urllib3==2.6.3
      - wcwidth==0.6.0
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
      - zipp==3.23.0
prefix: C:\Users\kohip\anaconda3\envs\mesh
